<a href="https://colab.research.google.com/github/shoxruxmamitov/navechok-paython/blob/main/arifmetik_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

kopaytirish , qoshish , bolish va h.k

In [20]:
kvv1 = np.arange(6).reshape(2, 3) # massiv yaratib olamiz
kvv2 = np.arange(6, 12).reshape(2, 3) # massiv yaratib olamiz

In [24]:
print(kvv1)

[[0 1 2]
 [3 4 5]]


In [26]:
print(kvv2)

[[ 6  7  8]
 [ 9 10 11]]


qoshish funksiasi

In [27]:
kvv1 + kvv2 # 2 ta massivni qoshib oldik

array([[ 6,  8, 10],
       [12, 14, 16]])

kopatma

In [28]:
kvv1*kvv2 # 2 ta massivni bir biriga kopatirdik

array([[ 0,  7, 16],
       [27, 40, 55]])

bolish

In [29]:
kvv2/kvv1 # 2 ta massivni bir biriga bolishdi

/tmp/ipython-input-2005690779.py:1: RuntimeWarning: divide by zero encountered in divide
  kvv2/kvv1


array([[inf, 7. , 4. ],
       [3. , 2.5, 2.2]])

ayirish

In [31]:
kvv2-kvv1 # 2 ta massivni bir biriga ayirdik

array([[6, 6, 6],
       [6, 6, 6]])

kvadratga oshirish

In [32]:
kvv1**2 # kvadratini topdik

array([[ 0,  1,  4],
       [ 9, 16, 25]])

In [33]:
kvv2**2

array([[ 36,  49,  64],
       [ 81, 100, 121]])

ildizini topish

In [34]:
kvv1**0.5 # ildizni topib oldik

array([[0.        , 1.        , 1.41421356],
       [1.73205081, 2.        , 2.23606798]])

In [35]:
kvv2**0.5

array([[2.44948974, 2.64575131, 2.82842712],
       [3.        , 3.16227766, 3.31662479]])

amaliot uchun

In [52]:
narh1 = np.arange(250).reshape(5, 50)
narh2 = np.arange(180).reshape(6, 30)

In [53]:
narh1

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29,  30,  31,  32,  33,  34,  35,  36,  37,  38,
         39,  40,  41,  42,  43,  44,  45,  46,  47,  48,  49],
       [ 50,  51,  52,  53,  54,  55,  56,  57,  58,  59,  60,  61,  62,
         63,  64,  65,  66,  67,  68,  69,  70,  71,  72,  73,  74,  75,
         76,  77,  78,  79,  80,  81,  82,  83,  84,  85,  86,  87,  88,
         89,  90,  91,  92,  93,  94,  95,  96,  97,  98,  99],
       [100, 101, 102, 103, 104, 105, 106, 107, 108, 109, 110, 111, 112,
        113, 114, 115, 116, 117, 118, 119, 120, 121, 122, 123, 124, 125,
        126, 127, 128, 129, 130, 131, 132, 133, 134, 135, 136, 137, 138,
        139, 140, 141, 142, 143, 144, 145, 146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
        163, 164, 165, 166, 167, 168, 169, 170, 171, 172, 173, 174, 175,
     

In [54]:
narh2

array([[  0,   1,   2,   3,   4,   5,   6,   7,   8,   9,  10,  11,  12,
         13,  14,  15,  16,  17,  18,  19,  20,  21,  22,  23,  24,  25,
         26,  27,  28,  29],
       [ 30,  31,  32,  33,  34,  35,  36,  37,  38,  39,  40,  41,  42,
         43,  44,  45,  46,  47,  48,  49,  50,  51,  52,  53,  54,  55,
         56,  57,  58,  59],
       [ 60,  61,  62,  63,  64,  65,  66,  67,  68,  69,  70,  71,  72,
         73,  74,  75,  76,  77,  78,  79,  80,  81,  82,  83,  84,  85,
         86,  87,  88,  89],
       [ 90,  91,  92,  93,  94,  95,  96,  97,  98,  99, 100, 101, 102,
        103, 104, 105, 106, 107, 108, 109, 110, 111, 112, 113, 114, 115,
        116, 117, 118, 119],
       [120, 121, 122, 123, 124, 125, 126, 127, 128, 129, 130, 131, 132,
        133, 134, 135, 136, 137, 138, 139, 140, 141, 142, 143, 144, 145,
        146, 147, 148, 149],
       [150, 151, 152, 153, 154, 155, 156, 157, 158, 159, 160, 161, 162,
        163, 164, 165, 166, 167, 168, 169, 170, 171,

In [56]:
np.exp(narh1)

array([[1.00000000e+000, 2.71828183e+000, 7.38905610e+000,
        2.00855369e+001, 5.45981500e+001, 1.48413159e+002,
        4.03428793e+002, 1.09663316e+003, 2.98095799e+003,
        8.10308393e+003, 2.20264658e+004, 5.98741417e+004,
        1.62754791e+005, 4.42413392e+005, 1.20260428e+006,
        3.26901737e+006, 8.88611052e+006, 2.41549528e+007,
        6.56599691e+007, 1.78482301e+008, 4.85165195e+008,
        1.31881573e+009, 3.58491285e+009, 9.74480345e+009,
        2.64891221e+010, 7.20048993e+010, 1.95729609e+011,
        5.32048241e+011, 1.44625706e+012, 3.93133430e+012,
        1.06864746e+013, 2.90488497e+013, 7.89629602e+013,
        2.14643580e+014, 5.83461743e+014, 1.58601345e+015,
        4.31123155e+015, 1.17191424e+016, 3.18559318e+016,
        8.65934004e+016, 2.35385267e+017, 6.39843494e+017,
        1.73927494e+018, 4.72783947e+018, 1.28516001e+019,
        3.49342711e+019, 9.49611942e+019, 2.58131289e+020,
        7.01673591e+020, 1.90734657e+021],
       [5.184

In [58]:
np.log(narh1)

/tmp/ipython-input-2421157725.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(narh1)


array([[      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
        1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458,
        2.30258509, 2.39789527, 2.48490665, 2.56494936, 2.63905733,
        2.7080502 , 2.77258872, 2.83321334, 2.89037176, 2.94443898,
        2.99573227, 3.04452244, 3.09104245, 3.13549422, 3.17805383,
        3.21887582, 3.25809654, 3.29583687, 3.33220451, 3.36729583,
        3.40119738, 3.4339872 , 3.4657359 , 3.49650756, 3.52636052,
        3.55534806, 3.58351894, 3.61091791, 3.63758616, 3.66356165,
        3.68887945, 3.71357207, 3.73766962, 3.76120012, 3.78418963,
        3.80666249, 3.8286414 , 3.8501476 , 3.87120101, 3.8918203 ],
       [3.91202301, 3.93182563, 3.95124372, 3.97029191, 3.98898405,
        4.00733319, 4.02535169, 4.04305127, 4.06044301, 4.07753744,
        4.09434456, 4.11087386, 4.12713439, 4.14313473, 4.15888308,
        4.17438727, 4.18965474, 4.20469262, 4.21950771, 4.2341065 ,
        4.24849524, 4.26267988, 4.27666612, 4.2

In [61]:
np.sqrt(narh2)

array([[ 0.        ,  1.        ,  1.41421356,  1.73205081,  2.        ,
         2.23606798,  2.44948974,  2.64575131,  2.82842712,  3.        ,
         3.16227766,  3.31662479,  3.46410162,  3.60555128,  3.74165739,
         3.87298335,  4.        ,  4.12310563,  4.24264069,  4.35889894,
         4.47213595,  4.58257569,  4.69041576,  4.79583152,  4.89897949,
         5.        ,  5.09901951,  5.19615242,  5.29150262,  5.38516481],
       [ 5.47722558,  5.56776436,  5.65685425,  5.74456265,  5.83095189,
         5.91607978,  6.        ,  6.08276253,  6.164414  ,  6.244998  ,
         6.32455532,  6.40312424,  6.4807407 ,  6.55743852,  6.63324958,
         6.70820393,  6.78232998,  6.8556546 ,  6.92820323,  7.        ,
         7.07106781,  7.14142843,  7.21110255,  7.28010989,  7.34846923,
         7.41619849,  7.48331477,  7.54983444,  7.61577311,  7.68114575],
       [ 7.74596669,  7.81024968,  7.87400787,  7.93725393,  8.        ,
         8.06225775,  8.1240384 ,  8.18535277,  8