<a href="https://colab.research.google.com/github/shoxruxmamitov/navechok-paython/blob/main/boolen_indekslash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

Boolen indekslash

In [ ]:
ismlar = np.array (['bexruz ', 'farrux ', 'shoxruh ', 'bekzod ', 'bexruz ', 'nurbek ', 'ulugbek ', 'bastam'])
ismlar # ismlar degan massiv hosil qildik

array(['bexruz ', 'farrux ', 'shoxruh ', 'bekzod ', 'bexruz ', 'nurbek ',
       'ulugbek ', 'bastam'], dtype='<U8')

omad massivini tuzamiz

In [ ]:
omad = np.random.rand(8, 3)
omad # omad degan massiv hosil qilib oldik

array([[4.36823823e-01, 6.03615538e-01, 9.03456867e-01],
       [2.17049620e-01, 8.43930268e-01, 3.56861679e-01],
       [6.14697807e-01, 5.45843816e-01, 4.87256672e-01],
       [7.16679436e-04, 1.69430153e-01, 2.52345563e-01],
       [8.33770145e-01, 6.23739467e-01, 1.49947635e-01],
       [6.55245314e-01, 9.66436841e-02, 8.24350324e-01],
       [3.39206302e-01, 2.07295498e-01, 4.35244611e-01],
       [7.16172480e-01, 9.56536079e-01, 2.61071355e-01]])

massivni ichida lugat borligni tekshiramiz

In [ ]:
ismlar == 'bexruz ' # bexruz lugatini ismlarda borligini tekshirib oldik va bizga true qilib berdi

array([ True, False, False, False,  True, False, False, False])

In [ ]:
ismlar == 'hasan ' # bunda False qilib berdi chunku massivni lugatida hasan ism mavjud emas edi

array([False, False, False, False, False, False, False, False])

Malumotlarni chiqaramiz

In [ ]:
omad = np.random.rand(8, 3)
omad[ismlar == 'farrux ']

TypeError: only integer scalar arrays can be converted to a scalar index