<a href="https://colab.research.google.com/github/shoxruxmamitov/navechok-paython/blob/main/chiziqli_algebrA.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

chiziqli algebra

In [1]:
import numpy as np

In [11]:
orderblok = np.array([[10., 11., 12., 13.], [14., 15., 16., 17.]])

In [12]:
orderblok # 2 va 4 qatorli massiv tuzdik

array([[10., 11., 12., 13.],
       [14., 15., 16., 17.]])

In [9]:
klassik = np.array([[18, 19, 20, 21], [22, 23, 24, 25,]])

In [15]:
klassik # 2 va 4 qatorli massiv tuzdik

array([[18, 19, 20, 21],
       [22, 23, 24, 25]])

In [17]:
orderblok + klassik # 2 ta massivni qoshadi

array([[28., 30., 32., 34.],
       [36., 38., 40., 42.]])

In [19]:
orderblok*3 # orderblok massivni har bitta elementini 3 ka kopatirib beradi

array([[30., 33., 36., 39.],
       [42., 45., 48., 51.]])

In [22]:
klassik * orderblok

array([[180., 209., 240., 273.],
       [308., 345., 384., 425.]])