<a href="https://colab.research.google.com/github/shoxruxmamitov/navechok-paython/blob/main/fayllar_bilan_ishlash.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

Fayllar bilan ishlash

In [26]:
import numpy as np

massiv yaratib olamiz

In [27]:
ilik = np.arange(31) # 0 va 30 gacha bolgan massiv yaratamiz

In [28]:
np.save('latta', ilik) # bir bir ozgaruvchi (latta) yaratib olamiz

In [29]:
ilik1 = np.load('latta.npy') # yana ozgaruvchi (ilik1) yaratib olamiz

In [30]:
ilik

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [31]:
ilik1 # ilik massiviga tegmay ilik1 massivga saxranit qilib ollik

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [32]:
lik = np.arange(20) # massiv yarartib olamiz

In [33]:
np.savez('orerblok', t = ilik , k = lik) # orerblokka (t) va (k) ozgaruchiga sax qilib olamiz

In [34]:
orerblok = np.load('orerblok.npz')

In [35]:
orerblok['t']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30])

In [36]:
orerblok['k']

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19])

In [37]:
np.savez_compressed('orerblok_comp.npz', t=ilik, k=lik)