<a href="https://colab.research.google.com/github/shoxruxmamitov/navechok-paython/blob/main/indekslash_va_kesish.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
arr = np.arange(10, 100, 10) #massiv yaratb oldik 10 dan 100 gacha 10 oralaigida

arr[-2] #-2 qilib 80 arr ni chiqarib oldik

np.int64(80)

oraliq elemntni kesib olish

In [ ]:
arr

array([10, 20, 30, 40, 50, 60, 70, 80, 90])

In [ ]:
arr[2:4] # 2 dan 5 gacha bolgan elementlarni kesib oladi

array([30, 40])


Numpy kutubxonasida massivning kesib olingan qismga o'zgartirish kirtilinsa, asosiy manba massivga ta'sir qiladi

In [ ]:
unvesal_arr = arr[2:4] # 2 dan 4 gacha bolgan elementni 1 ga ozgartirdik
unvesal_arr[:]=1
unvesal_arr

array([1, 1])

In [ ]:
arr

array([10, 20,  1,  1, 50,  0,  0,  0, 90])

In [ ]:
termit = arr[5:8] # 5 dan 8 gacha bolgan elementni 0 ga ozgartirdik
termit[:]=0
termit

array([0, 0, 0])

In [ ]:
arr

array([10, 20,  1,  1, 50,  0,  0,  0, 90])

copy usuli

In [ ]:
arr1 = np.arange(10, 200, 20)#massiv yaratik
arr1

array([ 10,  30,  50,  70,  90, 110, 130, 150, 170, 190])

In [ ]:
arr1[-3] #massivni funksiasini chiqarib oltik

np.int64(150)

In [ ]:
arr1 [2:4] # 2 va 4 orasi sonioni chiqarik

array([50, 70])

In [ ]:
retry_arr = arr1[2:6].copy() # funksiani 2 va 6 orasi sonlarni kopy 1 qilib oltik
retry_arr[:]=1
retry_arr

array([1, 1, 1, 1])

In [ ]:
arr1

array([ 10,  30,  50,  70,  90, 110, 130, 150, 170, 190])

In [ ]:
retry_arr

array([1, 1, 1, 1])

2-o'lchamli massivlarning bir nechta elementlarini kesib olish

In [ ]:
arr2d = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]])
arr2d # 2 olchamli massiv tuzdik

array([[ 1,  2,  3,  4],
       [ 5,  6,  7,  8],
       [ 9, 10, 11, 12]])

In [ ]:
arr2d[1, 3] # 1-qator 3-ustun fuksia sonini kesib oldik

np.int64(8)

In [ ]:
arr2d[0, 2]

np.int64(3)

3 massivni hosil qilamiz va kesib olamiz

In [ ]:
arr3d = np.array([[[1, 2, 3, 4],
                   [5, 6, 7, 8],
                   [9, 10, 11, 12]],

                  [[13, 14, 15, 16],
                   [17, 18, 19, 20],
                   [21, 22, 23, 24]],

                  [[25, 26, 27, 28],
                   [29, 30, 31, 32],
                   [33, 34, 35, 36]]])
arr3d # 3 maasivli arr tuzib oldik

array([[[ 1,  2,  3,  4],
        [ 5,  6,  7,  8],
        [ 9, 10, 11, 12]],

       [[13, 14, 15, 16],
        [17, 18, 19, 20],
        [21, 22, 23, 24]],

       [[25, 26, 27, 28],
        [29, 30, 31, 32],
        [33, 34, 35, 36]]])

In [ ]:
arr3d[1, 2,3] # 1-jadval 2-qator 3-ustunni kesib oldik

np.int64(24)

In [ ]:
arr3d[2][1, 0] # 2-jadval 1-qator 0-ustunni kesib oldik

np.int64(29)

In [ ]:
arr3d[0, 2, 3] #0-jadval 2-qator 3-ustunni kesib oldik

np.int64(12)

Amaliot uchun

In [ ]:
avtasalon = np.array([[[12, 21, 56, 76, 90, 31, 55, 89, 0],
                      [3, 75, 87, 23, 6789, 89, 367, 0, 0],
                      [6, 700, 63, 25, 800, 567, 26, 98, 6]],

                     [[678, 97, 135, 3567, 890, 35, 678, 78, 0],
                      [53, 68, 798, 156, 658, 87, 123, 56, 98],
                      [321, 567, 678, 907, 789, 356, 6799, 0, 0]],

                     [[876, 322, 678, 897, 211, 956, 86, 78, 987],
                      [3, 123, 8907, 900, 876, 567, 786, 512, 987],
                      [765, 97, 7, 9865, 76, 857, 866, 123, 965]]])
avtasalon

array([[[  12,   21,   56,   76,   90,   31,   55,   89,    0],
        [   3,   75,   87,   23, 6789,   89,  367,    0,    0],
        [   6,  700,   63,   25,  800,  567,   26,   98,    6]],

       [[ 678,   97,  135, 3567,  890,   35,  678,   78,    0],
        [  53,   68,  798,  156,  658,   87,  123,   56,   98],
        [ 321,  567,  678,  907,  789,  356, 6799,    0,    0]],

       [[ 876,  322,  678,  897,  211,  956,   86,   78,  987],
        [   3,  123, 8907,  900,  876,  567,  786,  512,  987],
        [ 765,   97,    7, 9865,   76,  857,  866,  123,  965]]])

In [ ]:
avtasalon[1][1, 5]

np.int64(87)

In [ ]:
avtasalon[2, 0, -2]

np.int64(78)

In [ ]:
avtasalon[-0][-1, -4]

np.int64(567)