<a href="https://colab.research.google.com/github/shoxruxmamitov/navechok-paython/blob/main/mantiqiy_shart_operatori.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

Tassavur qiling bizda ikkita ma'lumotlar (massivlar) mavjud bular: xarr va yarr. Agarda shart Trueni qanoatlantirsa xarr elementini qabul qilgan aksincha esa yarr elementini qabul qilgan yangi massiv hosil qilinsin.

In [7]:
xarr = np.array([1.1, 1.2, 1.3, 1.4, 1.5, 1.6, 1.7, 1.8, 1.9]) #massiv yarattik
yarr = np.array([2.1, 2.2, 2.3, 2.4, 2.5, 2.6, 2.7, 2.8, 2.9]) # massiv yarattik

In [8]:
anacon = np.array([True, False, True, False, True, True, False, True, False]) # xarr va yarr massiviga moslab anacon massivni yarattik

In [6]:
result = np.where(anacon, xarr, yarr) # result qiymatni ichiga (ancon , xarr va yarr ) massivni kirigizik
result # resultatni korishingiz mumkun

array([1.1, 2.2, 1.3, 2.4, 1.5, 1.6, 2.7, 1.8, 2.9])

where

In [9]:
tanoos = np.random.randn(6, 6)
tanoos # 6 ga 6 olchamli massiv yarattik

array([[ 7.41212164e-01,  6.44345124e-01, -6.13965111e-01,
        -7.32542116e-02,  6.04173958e-01, -9.95286430e-02],
       [ 2.64228706e-01, -4.78196987e-01, -1.10579468e+00,
         4.94653850e-01, -6.64888666e-01,  4.56159986e-01],
       [ 5.15814626e-01, -2.64256064e-01,  1.38543578e+00,
         4.37733123e-01,  1.67995568e-01,  9.90846913e-02],
       [-5.12983067e-01,  5.18742898e-01,  1.60243512e+00,
        -3.43103687e-01,  9.83349543e-01, -2.00049773e-01],
       [-8.34732604e-04,  1.51112347e+00, -1.16916644e+00,
        -1.94271172e+00,  1.89566187e+00, -1.63211803e+00],
       [ 9.79428847e-01, -5.39366000e-01,  9.73480298e-01,
        -8.15596643e-01,  1.84119620e+00, -1.30419724e+00]])

In [12]:
results = np.where(tanoos <0, -1, 1)
results # results massivini  manfiy sonini -1 ga musbat sonini 1 ga almashtirik

array([[ 1,  1, -1, -1,  1, -1],
       [ 1, -1, -1,  1, -1,  1],
       [ 1, -1,  1,  1,  1,  1],
       [-1,  1,  1, -1,  1, -1],
       [-1,  1, -1, -1,  1, -1],
       [ 1, -1,  1, -1,  1, -1]])

In [15]:
results2 = np.where(tanoos <0, -2, 2)
results2 # results2 massivini manfiy sonini -2 ga musbat sonini 2 ga almashtirik

array([[ 2,  2, -2, -2,  2, -2],
       [ 2, -2, -2,  2, -2,  2],
       [ 2, -2,  2,  2,  2,  2],
       [-2,  2,  2, -2,  2, -2],
       [-2,  2, -2, -2,  2, -2],
       [ 2, -2,  2, -2,  2, -2]])