<a href="https://colab.research.google.com/github/shoxruxmamitov/navechok-paython/blob/main/matematik_va_statistik_amallar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [34]:
import numpy as np


data

In [35]:
statis = np.random.randn(5, 4) # 5 ga 4 olchamli massiv ni chaqirib olamiz
statis

array([[-0.72808274,  0.15187559,  1.00543738,  0.38902457],
       [-0.29710155,  0.99964694,  0.21999674, -1.66949763],
       [-0.29378241,  0.15633274, -1.97127476, -0.31023308],
       [-0.13125278,  1.38736478,  0.70509254, -0.05489587],
       [ 2.36410144,  1.04700621,  0.76547333,  0.1455704 ]])

sum metodi

In [36]:
statis.sum() #statis massivni elementlarini barchasini max qimat qilib beradi

np.float64(3.8808018512069244)

In [37]:
np.sum(statis) # bu ikkinchi usuli boladi

np.float64(3.8808018512069244)

In [38]:
statis.sum(axis=1) # qator qimatarini sum ini hisoblab beradi

array([ 0.8182548 , -0.74695549, -2.41895751,  1.90630867,  4.32215138])

In [39]:
statis.sum(axis = 0) # ustun qimatlarini hioblab beradi

array([ 0.91388197,  3.74222626,  0.72472523, -1.50003161])

mean metodi

In [40]:
data = np.arange(10) # 0 dan 5 gacha bolgan massiv ni chaqirib oldik
data

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [41]:
mean = np.sum(data)
print(mean)

45


In [42]:
mean = np.sum(data)/len(data)
print(mean)

4.5


mean

In [43]:
statis

array([[-0.72808274,  0.15187559,  1.00543738,  0.38902457],
       [-0.29710155,  0.99964694,  0.21999674, -1.66949763],
       [-0.29378241,  0.15633274, -1.97127476, -0.31023308],
       [-0.13125278,  1.38736478,  0.70509254, -0.05489587],
       [ 2.36410144,  1.04700621,  0.76547333,  0.1455704 ]])

In [44]:
np.mean(statis) # massivni ortacha qimatini hosil qiladi

np.float64(0.1940400925603462)

In [45]:
np.mean(statis, axis = 0) # qator boyicha ortacha qiymatni hosil qiladi

array([ 0.18277639,  0.74844525,  0.14494505, -0.30000632])

In [46]:
statis.mean(axis= 0) # bu ikkinchi usuli

array([ 0.18277639,  0.74844525,  0.14494505, -0.30000632])

ustun hisoblash

In [47]:
np.mean(statis, axis=1) #ustun boyicha ortacha qiymatni hosil qildi

array([ 0.2045637 , -0.18673887, -0.60473938,  0.47657717,  1.08053784])

In [48]:
statis.mean(axis = 1) # bu ikkinchi usuli

array([ 0.2045637 , -0.18673887, -0.60473938,  0.47657717,  1.08053784])

cumsum

In [49]:
son = np.arange(10)
son

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [50]:
son.cumsum()

array([ 0,  1,  3,  6, 10, 15, 21, 28, 36, 45])