<a href="https://colab.research.google.com/github/shoxruxmamitov/numpy_kutubxonasi/blob/main/nump.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

In [2]:
a = np.array([10, 11, 12])
b = np.array([13, 14, 15])
c = np.array([16, 17, 18])

In [3]:
print(np.concatenate([a, b, c]))

[10 11 12 13 14 15 16 17 18]


In [4]:
s = np.array([[20, 21], [22, 23]])
t = np.array([[24, 25], [26, 27]])

In [5]:
print(np.hstack([s, t]))

[[20 21 24 25]
 [22 23 26 27]]


In [6]:
print(np.vstack([s, t]))

[[20 21]
 [22 23]
 [24 25]
 [26 27]]


In [7]:
matrix = np.array([[31, 32], [33, 34]])
print(matrix)

[[31 32]
 [33 34]]


In [8]:
print(np.prod(matrix))

1113024


In [9]:
tara = np.array([[52, 55], [62, 71]])
multiplier: int = 4

In [10]:
print(tara * multiplier)

[[208 220]
 [248 284]]


In [11]:
arr = np.array([1, 1, 2, 2, 3, 3, 4, 4, 5, 6])
print(np.unique(arr, return_index=True))

(array([1, 2, 3, 4, 5, 6]), array([0, 2, 4, 6, 8, 9]))


In [12]:
print(np.unique(arr, return_counts=True))

(array([1, 2, 3, 4, 5, 6]), array([2, 2, 2, 2, 1, 1]))


In [13]:
uxx = np.arange(10)
print(np.flip(uxx))

[9 8 7 6 5 4 3 2 1 0]


In [14]:
ploat = np.array([1.01, 2.5, 3.99])

In [15]:
print(np.sqrt(ploat))
print(np.round(ploat))
print(np.ceil(ploat))
print(np.floor(ploat))

[1.00498756 1.58113883 1.99749844]
[1. 2. 4.]
[2. 3. 4.]
[1. 2. 3.]


In [16]:
konsta = np.array([[['A', 'B', 'C'], ['E', 'F', 'G'], ['H', 'J', 'K'],
                    ['L', 'M', 'N'], ['O', 'P', 'Q'], ['R', 'S', 'T'],
                    ['U', 'V', 'W'], ['X', 'Y', 'Z'], ['SH', 'CH', ' ']]])

In [17]:
worik = konsta[0, 0, 0] + konsta[0, 1, 0] + konsta[0, 2, 0]
print(worik)

AEH


In [18]:
polo = np.array([[1, 2, 3, 4, 5],
                 [6, 7, 8, 9, 10]])

In [19]:
print(np.sum(polo))
print(np.mean(polo))
print(np.std(polo))
print(np.var(polo))
print(np.min(polo))
print(np.max(polo))
print(np.argmin(polo))
print(np.argmax(polo))

55
5.5
2.8722813232690143
8.25
1
10
0
9


In [20]:
massivlar = np.array([[12, 23, 2, 1],
                        [53, 56, 67, 31],
                        [997, 61, 89,67],
                        [90, 91, 92, 95],
                        ])

In [21]:
massivlar

array([[ 12,  23,   2,   1],
       [ 53,  56,  67,  31],
       [997,  61,  89,  67],
       [ 90,  91,  92,  95]])

In [22]:
print(massivlar.ndim)
print(massivlar.shape)
print(massivlar.size)

2
(4, 4)
16


In [23]:
print(massivlar[0:1])

[[12 23  2  1]]


In [24]:
print(massivlar[::2])

[[ 12  23   2   1]
 [997  61  89  67]]


In [26]:
a1 = np.empty((5, 5, 5))
a1

array([[[4.87043969e-315, 0.00000000e+000, 5.76851285e-317,
         6.87672574e-310, 6.87672574e-310],
        [5.76851285e-317, 6.87672575e-310, 6.87672574e-310,
         6.87672574e-310, 6.87672574e-310],
        [5.76851285e-317, 6.87672574e-310, 6.87672574e-310,
         6.87672574e-310, 5.76851285e-317],
        [6.87672575e-310, 6.87672575e-310, 6.87672574e-310,
         6.87672575e-310, 6.87672574e-310],
        [5.76851285e-317, 6.87672566e-310, 6.87672566e-310,
         6.87672574e-310, 6.87672574e-310]],

       [[6.87672566e-310, 6.87672574e-310, 6.87672574e-310,
         6.87672566e-310, 6.87672575e-310],
        [6.87672575e-310, 6.87672575e-310, 6.87672575e-310,
         6.87672575e-310, 6.87672574e-310],
        [6.87672566e-310, 6.87672574e-310, 6.87672574e-310,
         6.87672574e-310, 6.87672574e-310],
        [6.87672574e-310, 6.87672575e-310, 6.87672574e-310,
         6.87672574e-310, 6.87672566e-310],
        [6.87672574e-310, 6.87672575e-310, 6.87672566e-310,
  

In [27]:
rng = np.random.default_rng()

In [29]:
ranking = np.array(['apple', 'banana', 'orange', 'coconut', 'pineapple'])
ranking = rng.choice(ranking, size=(3, 3))
print(ranking)

[['orange' 'coconut' 'pineapple']
 ['pineapple' 'apple' 'apple']
 ['pineapple' 'banana' 'orange']]


In [34]:
birlik = np.ones((6, 5, 2))
birlik

array([[[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]],

       [[1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.],
        [1., 1.]]])

In [36]:
nolik = np.zeros((6, 5, 2))
nolik

array([[[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]],

       [[0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.],
        [0., 0.]]])

In [37]:
ochirish = np.array([[12, 31, 20],
                     [42, 35, 56]])
ochirish

array([[12, 31, 20],
       [42, 35, 56]])

In [39]:
print(np.delete(ochirish, 1, 1))

[[12 20]
 [42 56]]


In [45]:
w = np.array([7, 8, 9])
w = np.append(w, [13, 14, 15])
w = np.insert(w, 3, [10, 11, 12])

In [46]:
w

array([ 7,  8,  9, 10, 11, 12, 13, 14, 15])