<a href="https://colab.research.google.com/github/shoxruxmamitov/navechok-paython/blob/main/Nump_va_array.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
data = [2, 5.5 , 6, 9, 1,0, 18] # array orqali massiv yaratib ollik
arr = np.array(data)
arr

array([ 2. ,  5.5,  6. ,  9. ,  1. ,  0. , 18. ])

In [ ]:
data

[2, 5.5, 6, 9, 1, 0, 18]

In [ ]:
data1 = ['ser ', 'kerv ', 'mira ', 'tgir ', ]
arr1 = np.array(data1)
arr1

array(['ser ', 'kerv ', 'mira ', 'tgir '], dtype='<U5')

Massiv olchami

In [ ]:
arr.ndim # massivni olchamini hisoblandi

1

In [ ]:
arr1.ndim #massivni olchami kelib chiqardik

1

2 va undan ortiq massiv hosil qilamiz

In [ ]:
data2 = [[12, 56, 78, 89], [31, 75, 92, 61]] # 2 qatorli massiv hosil qildik
arr2 = np.array(data2)
arr2

array([[12, 56, 78, 89],
       [31, 75, 92, 61]])

In [ ]:
arr2.ndim # massivni olchamini hisobladik

2

Shape va size metodi

In [ ]:
arr2.shape #massivni qator va ustunini korsatadi

(2, 4)

In [ ]:
arr2.size #massivni elementlar soni

8

zeros va ones

In [ ]:
arr3 = np.zeros((2, 4)) #barcha elementi 0 ga teng bolgan ustun chiqaradi
arr3

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.]])

In [ ]:
arr4 = np.ones((2, 4)) #barcha elementi 1 ga teng bolgan ustun chiqaradi
arr4

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.]])

arange funksiasi orqali chiqaramiz

In [ ]:
arr5 = np.arange(12, 100, 5) #arange funksiasi 12 dan 100 gacha 5 tadan tashab chiqaradi
arr5

array([12, 17, 22, 27, 32, 37, 42, 47, 52, 57, 62, 67, 72, 77, 82, 87, 92,
       97])

In [ ]:
arr6 = np.arange(23)#0 dan 23 gacha bolgan sonlarni chiqaradi
arr6

array([ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 16,
       17, 18, 19, 20, 21, 22])

random funksiasi orqali chiqarish (randn , randint, rand)

In [ ]:
arr7 = np.random.randn(2, 3) # 2-3 olchamli element{ 0-1 } qimatlarran tashkil topgan
arr7

array([[-0.22593023, -0.28969776, -0.03632732],
       [-0.29887908,  0.25346843,  0.58941685]])

In [ ]:
arr8 = np.random.randint(10, size=(2, 3)) #(2 va 3) olchamli va max qimati 10 bolgan int sonlar
arr8

array([[5, 2, 5],
       [2, 1, 9]])

In [ ]:
arr9 = np.random.rand(2, 3) # (2, 3) olchamli elementlari  (normal-dist
arr9

array([[0.25156671, 0.53170468, 0.3120988 ],
       [0.49936067, 0.08461858, 0.03029599]])

random amaliot

In [ ]:
opp = np.random.randn(3, 5)
opp

array([[ 0.11674082, -0.43139092, -1.39148711,  1.35219424, -0.05081165],
       [-2.43956088,  0.73753716,  0.71627817,  1.59742816, -1.06254341],
       [-0.80039713,  1.09839084,  1.17290369, -0.83762272, -0.33049635]])

In [ ]:
opp1 = np.random.randint(100, size=(5, 7))
opp1

array([[95, 12, 18,  8, 37, 80, 49],
       [99, 35,  1, 41, 16, 80,  7],
       [91, 18, 81, 89, 43, 70, 18],
       [35, 74, 25, 95, 73, 47, 24],
       [ 6, 26, 24, 75, 17, 99, 23]])

In [ ]:
opp2 = np.random.randn(6, 2)
opp2

array([[ 0.03283284,  0.01097885],
       [ 0.74610754,  2.05480923],
       [ 0.49837528,  0.16474364],
       [-0.30174168,  1.18353491],
       [-1.28237946, -0.03913778],
       [ 0.80151871, -0.80008404]])