<a href="https://colab.research.google.com/github/shoxruxmamitov/navechok-paython/blob/main/tartiblash_sorting.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

massiv

In [3]:
tartib = np.random.rand(5)
tartib

array([0.76387273, 0.38578363, 0.32450349, 0.34000018, 0.16475484])

sort funksiasi

In [6]:
tartib.sort() # elementni tartiblangan varianti
tartib


array([0.16475484, 0.32450349, 0.34000018, 0.38578363, 0.76387273])

In [8]:
-np.sort(-tartib) #elementni teskari tartiblangan varianti

array([0.76387273, 0.38578363, 0.34000018, 0.32450349, 0.16475484])

massiv hosil qilamiz

In [11]:
mojiza = np.random.randn(3,4)
mojiza

array([[-0.09436118,  0.40578919,  0.22046635, -0.12071598],
       [-1.24017853,  0.8999031 , -1.44280151, -1.88449441],
       [ 0.01951456, -0.0207877 , -0.80769561,  1.6498912 ]])

qator

In [15]:
np.sort(mojiza, axis=0) # qator boicha tartiblangan korinishi

array([[-1.24017853, -0.0207877 , -1.44280151, -1.88449441],
       [-0.09436118,  0.40578919, -0.80769561, -0.12071598],
       [ 0.01951456,  0.8999031 ,  0.22046635,  1.6498912 ]])

ustun boicha tartiblangan korinishi

In [17]:
np.sort(mojiza, axis = 1) #ustun boicha tartiblangan korinishi

array([[-0.12071598, -0.09436118,  0.22046635,  0.40578919],
       [-1.88449441, -1.44280151, -1.24017853,  0.8999031 ],
       [-0.80769561, -0.0207877 ,  0.01951456,  1.6498912 ]])

amaliot uchun

In [21]:
amali = np.random.rand(12)
amali

array([0.04484168, 0.55474235, 0.77725214, 0.25517648, 0.29112496,
       0.56791379, 0.57292832, 0.97123528, 0.9888043 , 0.71761271,
       0.74998917, 0.42313373])

In [22]:
np.sort(amali)

array([0.04484168, 0.25517648, 0.29112496, 0.42313373, 0.55474235,
       0.56791379, 0.57292832, 0.71761271, 0.74998917, 0.77725214,
       0.97123528, 0.9888043 ])

In [24]:
-np.sort(-amali)

array([0.9888043 , 0.97123528, 0.77725214, 0.74998917, 0.71761271,
       0.57292832, 0.56791379, 0.55474235, 0.42313373, 0.29112496,
       0.25517648, 0.04484168])

In [28]:
kanik = np.random.randn(5,3)
kanik

array([[-0.53330836, -0.94360101,  1.38063715],
       [-0.54390459,  0.43729736,  2.15403092],
       [-0.18720632, -0.73400672,  0.29088866],
       [ 0.72615267,  0.10626238, -0.33218747],
       [-0.71065106,  1.58826797,  0.19200693]])

In [29]:
np.sort(kanik)

array([[-0.94360101, -0.53330836,  1.38063715],
       [-0.54390459,  0.43729736,  2.15403092],
       [-0.73400672, -0.18720632,  0.29088866],
       [-0.33218747,  0.10626238,  0.72615267],
       [-0.71065106,  0.19200693,  1.58826797]])

In [30]:
np.sort(kanik, axis=0)

array([[-0.71065106, -0.94360101, -0.33218747],
       [-0.54390459, -0.73400672,  0.19200693],
       [-0.53330836,  0.10626238,  0.29088866],
       [-0.18720632,  0.43729736,  1.38063715],
       [ 0.72615267,  1.58826797,  2.15403092]])

In [31]:
np.sort(kanik, axis=1)

array([[-0.94360101, -0.53330836,  1.38063715],
       [-0.54390459,  0.43729736,  2.15403092],
       [-0.73400672, -0.18720632,  0.29088866],
       [-0.33218747,  0.10626238,  0.72615267],
       [-0.71065106,  0.19200693,  1.58826797]])