<a href="https://colab.research.google.com/github/shoxruxmamitov/navechok-paython/blob/main/unversal_funksialar.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [33]:
import numpy as np

sqrt, square, exp, log, modf, sign, isnan

In [34]:
son = np.arange(10) # 0 dan 10 gacha sonni chiqarib oldik
son

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

sqrt

In [35]:
np.sqrt(son) # son ning barcha elementni ildizini topadi

array([0.        , 1.        , 1.41421356, 1.73205081, 2.        ,
       2.23606798, 2.44948974, 2.64575131, 2.82842712, 3.        ])

square

In [36]:
np.square(son) # elementni kvadrat ildizni topadi

array([ 0,  1,  4,  9, 16, 25, 36, 49, 64, 81])

exp

In [37]:
np.exp(son) # eksponentini topadi

array([1.00000000e+00, 2.71828183e+00, 7.38905610e+00, 2.00855369e+01,
       5.45981500e+01, 1.48413159e+02, 4.03428793e+02, 1.09663316e+03,
       2.98095799e+03, 8.10308393e+03])

log

In [38]:
np.log(son) # logorofimini topadi

/tmp/ipython-input-1086485451.py:1: RuntimeWarning: divide by zero encountered in log
  np.log(son) # logorofimini topadi


array([      -inf, 0.        , 0.69314718, 1.09861229, 1.38629436,
       1.60943791, 1.79175947, 1.94591015, 2.07944154, 2.19722458])

modf # bu funksia sonlarni qoldiq va butun ni ajratib beradi

In [39]:
tasodif_son=np.random.randn(6)
tasodif_son

array([ 1.54584898, -0.47053976,  0.86777328,  0.6371266 , -0.88563805,
       -1.9279581 ])

In [40]:
qoldiq, butun = np.modf(tasodif_son)

In [41]:
print(qoldiq) # qoldiq sonni ajratib berdi
print(butun)  # butun sonni ajratib berdi

[ 0.54584898 -0.47053976  0.86777328  0.6371266  -0.88563805 -0.9279581 ]
[ 1. -0.  0.  0. -0. -1.]


sign # funksiasi sonni manfi (-1) va musbat (1) sonini qataradi

In [42]:
np.sign(tasodif_son)

array([ 1., -1.,  1.,  1., -1., -1.])

Isnan funksiasi elementda Nan funksiasi bolsa True qataradi bolmasa False qataradi

In [43]:
tasodif_son

array([ 1.54584898, -0.47053976,  0.86777328,  0.6371266 , -0.88563805,
       -1.9279581 ])

In [44]:
np.isnan(tasodif_son)

array([False, False, False, False, False, False])

In [45]:
tasodif_son[2]=np.nan

In [46]:
np.isnan(tasodif_son)

array([False, False,  True, False, False, False])

Binari funksia 2 ta element ni qabul qiluvchi funksia

ad funksiasi

In [47]:
# 2ta tasodifi massiv hosil qilamiz
tasodif1 = np.random.rand(5)
tasodif2 = np.random.rand(5)

In [48]:
tasodif1

array([0.23797208, 0.18135497, 0.54062533, 0.0886309 , 0.82145167])

In [49]:
tasodif2

array([0.06570814, 0.53453359, 0.50463812, 0.27702724, 0.84543678])

In [50]:
np.add(tasodif1, tasodif2) # 2 ta massivni bir biriga qoshib chiqdi

array([0.30368022, 0.71588856, 1.04526345, 0.36565813, 1.66688845])

In [51]:
tasodif1 + tasodif2 # bu ham qoshish funksiasi

array([0.30368022, 0.71588856, 1.04526345, 0.36565813, 1.66688845])

multiply # 2 ta massivni bir biriga kopaytmasi

In [52]:
np.multiply(tasodif1, tasodif2) # massivni kopaytirilli

array([0.0156367 , 0.09694032, 0.27282015, 0.02455317, 0.69448545])

In [53]:
tasodif1*tasodif2 # bu ham ikkinchi usuli

array([0.0156367 , 0.09694032, 0.27282015, 0.02455317, 0.69448545])

maxsimum # 2 ta massivni bir biriga moslab max qiymatini qaytaradi

In [54]:
np.maximum(tasodif1, tasodif2) # max qimatini chiqarib beradi

array([0.23797208, 0.53453359, 0.54062533, 0.27702724, 0.84543678])